CREATE TABLE IF NOT EXISTS t_users
(
    ID       INT            NOT NULL AUTO_INCREMENT,
    USERNAME     VARCHAR(255)   NOT NULL,
    PASSWORD VARCHAR(255)   NOT NULL,
    EMAIL    VARBINARY(255) NOT NULL,
    GENDER   SMALLINT       NOT NULL,
    PRIMARY KEY PK_USER (ID),
    INDEX IDX_NAME (USERNAME),
    CONSTRAINT UNIQUE UNIQ_NAME (USERNAME)
);
